version: '3.8'

services:
#  app:
#    container_name: kjtp-project
#    build:
#      context: .
#      dockerfile: Dockerfile
#      target: dev
#    image: kjtp-project-dev
#    ports:
#      - "8080:8080"
#    environment:
#      - PROTOCOL=http
#      - KEYCLOAK_HOST=localhost
#      - KEYCLOAK_PORT=8081
#      - KEYCLOAK_ADMIN_USER=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#      - DATABASE_HOST=kjtp-app-db
#      - DATABASE_NAME=kjtp-admin
#      - DATABASE_USER=873264ygy!@E
#      - DATABASE_PASSWORD=
#    restart: always
#    networks:
#      - kjtp-project-network

  app-db:
    container_name: kjtp-app-db
    image: postgres:16-alpine3.18
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=kjtp-app_db
      - POSTGRES_USER=kjtp-admin
      - POSTGRES_PASSWORD=873264ygy!@E
    volumes:
      - project-db-volume:/var/lib/postgresql/data
    networks:
      - kjtp-project-network
    restart: always

  keycloak:
    container_name: kjtp-keycloak
    image: bitnami/keycloak:22.0.5
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_HTTP_PORT=8081
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_VENDOR=postgresql
      - KEYCLOAK_DATABASE_HOST=kjtp-keycloak-db
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak_db
      - KEYCLOAK_DATABASE_USER=keycloak_admin
      - KEYCLOAK_DATABASE_PASSWORD=872r#@6afb
    depends_on:
      - keycloak-db
    networks:
      - kjtp-project-network
    restart: always

  keycloak-db:
    container_name: kjtp-keycloak-db
    image: postgres:16-alpine3.18
    environment:
      - POSTGRES_DB=keycloak_db
      - POSTGRES_USER=keycloak_admin
      - POSTGRES_PASSWORD=872r#@6afb
    volumes:
      - keycloak-db-volume:/var/lib/postgresql/data
    networks:
      - kjtp-project-network
    restart: always

volumes:
  project-db-volume:
    external: false
  keycloak-db-volume:
    external: false

networks:
  kjtp-project-network: